# Generated by Django 6.1 on 2026-08-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('quantidade_exemplares', models.IntegerField(verbose_name='Quantidade de Exemplares')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
        ),
    ]
