# Generated by Django 6.1 on 2026-08-05 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_solicitante', models.CharField(max_length=150, verbose_name='Nome do Aluno/Funcionário')),
                ('data_empréstimo', models.DateField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Devolvido')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro', verbose_name='Livro')),
            ],
        ),
    ]
