# Generated by Django 6.1 on 2026-08-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_empréstimo',
            new_name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='nome_solicitante',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='cpf',
            field=models.CharField(default='', max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='email',
            field=models.EmailField(default='000.000.000-00', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='endereco',
            field=models.CharField(default='Não informado', max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='nome_completo',
            field=models.CharField(default='Usuário Padrão', max_length=150, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='rg',
            field=models.CharField(default='Usuário', max_length=20, verbose_name='RG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='telefone',
            field=models.CharField(default='0000-0000', max_length=20, verbose_name='Telefone de Contato'),
            preserve_default=False,
        ),
    ]
