# Generated by Django 6.0.6 on 2026-08-10 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_rename_data_empréstimo_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_emprestimo']},
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='livros.livro', verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AddIndex(
            model_name='emprestimo',
            index=models.Index(fields=['cpf', 'devolvido'], name='livros_empr_cpf_ac2622_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['disponivel'], name='livros_livr_disponi_a72ae6_idx'),
        ),
    ]
