# Generated by Django 6.1 on 2026-08-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_mensagemsuporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='RG'),
        ),
    ]
